spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:63792}
  cache:
    type: redis
    redis:
      time-to-live: PT60S
lotto:
  result-checker:
    facade:
      minutesToWaitForResults: 5
  number-generator:
    scheduler:
      cron: "0 0 12 * * SAT" # every Saturday at 12:00
    facade:
      maximalWinningNumber: 99
      minimalWinningNumber: 1
      count: 25
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
          connectionTimeout: 7000
          readTimeout: 7000

auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration-time: 30