spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web

lotto:
  number-generator:
    scheduler:
      cron: "0 0 12 * * SAT" # every Saturday at 12:00
    facade:
      maximalWinningNumber: 99
      minimalWinningNumber: 1
      count: 25
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
          connectionTimeout: 7000
          readTimeout: 7000
