spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: PT1S
lotto:
  number-generator:
    http:
      client:
        config:
          uri: http://localhost
          port: 80
    scheduler:
      cron: "*/1 * * * * *" # every 1 second

auth:
  jwt:
    secret: ${JWT_SECRET}