spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web

lotto:
  number-generator:
    http:
      client:
        config:
          uri: http://localhost
          port: 80
    scheduler:
      cron: "*/1 * * * * *" # every 1 second
